version: '3.1'

services:


 drupal :
    image: nginx:latest 
    ports:
       - '8080:80'
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites



  postgres:
   image : postgres:latest
    enviroment:
   - POSTGRES_PASSWORD: paswword
    image: postgres:latest 
    