apiVersion: v1
kind: Service
metadata: 
  name: home-assistant-service
spec:
  type: NodePort
  ports:
  - port: 8123
  selector:
    app: app-home-assistant
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: app-home-assistant-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-home-assistant
  template:
    metadata:
      labels:
        app: app-home-assistant
    spec:
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:stable
        ports:
        - containerPort: 8123

