apiVersion: v1
kind: Pod
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    name: home-assistant
spec:
  containers:
  - name: home-assistant
    image: homeassistant/home-assistant:stable
    ports:
    - containerPort:  8123
    volumeMounts:
    - mountPath: /config
      name: homeassistant
  volumes:
  - name: homeassistant
    hostPath:
      # Ensure the file directory is created.
      path: /C/Users/{UserName}/homeassistant
      type: DirectoryOrCreate