
#Creates Pod in chosen namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment #Deplyment name
  namespace: test-namespace #Namespace name
  labels:
    name: test #Label name
spec:
  selector:
   matchLabels:
    app: test
  replicas: 5
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: pod-test
        image: nginx:latest
        ports:
        - containerPort: 80
