apiVersion: v1
kind: Pod
metadata:
  name: home-assistant
  namespace: default
  labels:
    name: home-assistant
spec:
  containers:
  - name: home-assistant
    image: homeassistant/home-assistant:stable
    ports:
    - containerPort:  8123
    volumeMounts:
    - mountPath: /home/arie/homeassistans
      name: homeassistant
    - mountPath: /home/arie/homeassistans/configuration.yaml
      name: config
  volumes:
  - name: homeassistant
    hostPath:
      # Ensure the file directory is created.
      path: /home/arie/homeassistans
      type: DirectoryOrCreate
  - name: config
    hostPath:
        path: /home/arie/homeassistans/configuration.yaml
        type: FileOrCreate
