apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-pv-claim
  namespace: home
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi