apiVersion: v1
kind: PersistentVolume
metadata:
 name: home-pv
 namespace: home
 labels:
   type: local
spec:
 storageClassName: manual
 capacity: 
   storage: 100Mi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: "/home/arie/homeassistant"


